// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EventDocumentDataSlicesSlice = never;

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Titre field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: event.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Date et heure field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Date et heure
   * - **API ID Path**: event.date_event
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date_event: prismic.TimestampField;

  /**
   * Type field in *Event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Type
   * - **API ID Path**: event.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    "Activitée" | "Nuit d'observation" | "Conférence" | "Atelier"
  >;

  /**
   * Afficher informations field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: event.display_author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_author: prismic.BooleanField;

  /**
   * Intervenant (conférence & atelier) field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Intervenant (conférence & atelier)
   * - **API ID Path**: event.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Spécialité de l'intervenant field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Spécialité de l'intervenant
   * - **API ID Path**: event.author_job
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_job: prismic.KeyTextField;

  /**
   * Photo intervenant field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.photo_intervenant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_intervenant: prismic.ImageField<never>;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description de l'intervention
   * - **API ID Path**: event.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice> /**
   * Meta Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Item in *Homepage → Galerie*
 */
export interface HomepageDocumentDataGalleryItem {
  /**
   * Image field in *Homepage → Galerie*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Ouvrir le site field in *Homepage*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.enable_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  enable_site: prismic.BooleanField;

  /**
   * Titre field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sous-titre field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sous-titre
   * - **API ID Path**: homepage.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Logo field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Date de début field in *Homepage*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date de début
   * - **API ID Path**: homepage.date_start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_start: prismic.DateField;

  /**
   * Date de fin field in *Homepage*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date de fin
   * - **API ID Path**: homepage.date_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_end: prismic.DateField;

  /**
   * Lien inscription field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Lien d'inscription
   * - **API ID Path**: homepage.subscribe_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subscribe_link: prismic.LinkField;

  /**
   * Texte de présentation field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Présentation
   * - **API ID Path**: homepage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image de présentation field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.image_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_description: prismic.ImageField<never>;

  /**
   * Nom du lieu field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom du lieu
   * - **API ID Path**: homepage.place_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place_name: prismic.KeyTextField;

  /**
   * Coordonnées géographiques field in *Homepage*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.place_coords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  place_coords: prismic.GeoPointField;

  /**
   * Galerie field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<HomepageDocumentDataGalleryItem>>;

  /**
   * Lien youtube field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Lien youtube
   * - **API ID Path**: homepage.youtube_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_link: prismic.LinkField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<"thumbs">;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice = never;

/**
 * Content for Landing page documents
 */
interface LandingPageDocumentData {
  /**
   * Titre field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: landing_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image de présentation field in *Landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.header_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * Contenu field in *Landing page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contenu
   * - **API ID Path**: landing_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Landing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

type RateDocumentDataSlicesSlice = never;

/**
 * Content for Tarif documents
 */
interface RateDocumentData {
  /**
   * Position d'affichage field in *Tarif*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Position d'affichage
   * - **API ID Path**: rate.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  position: prismic.NumberField;

  /**
   * Afficher field in *Tarif*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: rate.display
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display: prismic.BooleanField;

  /**
   * Titre field in *Tarif*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: rate.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Tarif*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rate.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"vignette">;

  /**
   * Description field in *Tarif*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description
   * - **API ID Path**: rate.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Prix (euro) field in *Tarif*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Prix en euro
   * - **API ID Path**: rate.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Camping field in *Tarif*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Camping
   * - **API ID Path**: rate.camping
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  camping: prismic.KeyTextField;

  /**
   * Nombre de nuits field in *Tarif*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Nombre de nuits
   * - **API ID Path**: rate.nights
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  nights: prismic.NumberField;

  /**
   * Nombre de jours field in *Tarif*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Nombre de jours
   * - **API ID Path**: rate.days
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  days: prismic.NumberField;

  /**
   * Slice Zone field in *Tarif*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rate.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RateDocumentDataSlicesSlice> /**
   * Meta Title field in *Tarif*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rate.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Tarif*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rate.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Tarif*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rate.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Tarif document from Prismic
 *
 * - **API ID**: `rate`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RateDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RateDocumentData>, "rate", Lang>;

export type AllDocumentTypes =
  | EventDocument
  | HomepageDocument
  | LandingPageDocument
  | RateDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataGalleryItem,
      HomepageDocumentDataSlicesSlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      RateDocument,
      RateDocumentData,
      RateDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
